---

- hosts: linux
  remote_user: me
  tasks:
    - name: Get IP
      shell: ip a
      register: task1_result
    - debug:
        var: task1_result.stdout_lines

- hosts: windows
  tasks:
    - name: Get IP
      win_command: ipconfig /all
      register: task1_result
    - debug:
        var: task1_result.stdout_lines
