---

- hosts: winserver
  tasks:
    - name: Getting Windows Server installed components
      win_shell: echo SELECT data AS "Installed Server Components" FROM registry WHERE key IN (SELECT key FROM registry WHERE path LIKE 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ServerManager\ServicingStorage\ServerComponentCache\%\InstallState' AND data = '1') AND path LIKE '%DisplayName'; | osqueryi
      args:
        executable: cmd
      register: winserver_installed
    - debug:
        var: winserver_installed.stdout_lines

- hosts: linux
  tasks:
    - name: Getting Linux packages
      shell: echo "SELECT name FROM deb_packages;" | osqueryi
      register: linux_packages
    - debug:
        var: linux_packages.stdout_lines

    - name: Getting Linux startup items
      shell: echo "SELECT name, path FROM processes WHERE parent = 1;" | osqueryi
      register: linux_startup
    - debug:
        var: linux_startup.stdout_lines

- hosts: windows
  tasks:
    - name: Getting Windows installed softwares
      win_shell: echo SELECT name FROM programs UNION SELECT name from chocolatey_packages; | osqueryi
      args:
        executable: cmd
      register: win_installed
    - debug:
        var: win_installed.stdout_lines

    - name: Getting Windows startup items
      win_shell: echo SELECT name, path, status, username FROM startup_items; | osqueryi
      args:
        executable: cmd
      register: win_startup
    - debug:
        var: win_startup.stdout_lines
