---

#- hosts: linux
#  tasks:
#    - name: Getting Linux hostnames
#      shell: echo "SELECT hostname FROM system_info;" | osqueryi
#      register: linux_hostnames
#    - debug:
#        var: linux_hostnames.stdout_lines
#
#    - name: Getting Linux OS info
#      shell: echo "SELECT name, patch FROM os_version;" | osqueryi
#      register: linux_os
#    - debug:
#        var: linux_os.stdout_lines
#
#    - name: Getting Linux IP addresses
#      shell: echo "SELECT address FROM interface_addresses;" | osqueryi
#      register: linux_ip
#    - debug:
#        var: linux_ip.stdout_lines
#
#    - name: Getting Linux users
#      shell: echo "SELECT username FROM users;" | osqueryi
#      register: linux_users
#    - debug:
#        var: linux_users.stdout_lines
#
- hosts: winserver
  tasks:
    - name: Getting Windows Server installed components
      win_shell: echo SELECT data AS "Installed Server Components" FROM registry WHERE key IN (SELECT key FROM registry WHERE path LIKE 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ServerManager\ServicingStorage\ServerComponentCache\%\InstallState' AND data = '1') AND path LIKE '%DisplayName'; | osqueryi
      args:
        executable: cmd
      register: winserver_installed
    - debug:
        var: winserver_installed.stdout_lines

#    - name: Getting Windows OS info
#      win_shell: echo SELECT name, patch FROM os_version; | osqueryi
#      args:
#        executable: cmd
#      register: win_os
#    - debug:
#        var: win_os.stdout_lines
#
#    - name: Getting Windows IP addresses
#      win_shell: echo SELECT address FROM interface_addresses; | osqueryi
#      args:
#        executable: cmd
#      register: win_ip
#    - debug:
#        var: win_ip.stdout_lines
#
#    - name: Getting Windows users
#      win_shell: echo SELECT username FROM users; | osqueryi
#      args:
#        executable: cmd
#      register: win_users
#    - debug:
#        var: win_users.stdout_lines
#
